services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Newageerp\SfReactTemplates\CoreTemplates\:
    resource: '../CoreTemplates/*'
    arguments: [ ]
  Newageerp\SfReactTemplates\Template\:
    resource: '../Template/*'
    arguments: [ ]
  Newageerp\SfReactTemplates\Controller\:
    resource: '../Controller/*'
    arguments: [ ]
  template_evt_service:
    namespace: App\Template\
    resource: "../src/Templates/**/*TemplateEvt"
    tags:
      - {name: "kernel.event_listener"}